spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: planner-todo
              uri: lb://PLANNER-TODO
              predicates:
                - Path=/planner-todo/**
