spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: planner-todo
              uri: lb://PLANNER-TODO
              predicates:
                - Path=/planner-todo/**
            - id: planner-users
              uri: lb://PLANNER-USERS
              predicates:
                - Path=/planner-users/**
